# Generated by Django 5.2.5 on 2025-09-22 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriarestaurante',
            name='icono',
            field=models.CharField(default='🍽️', max_length=50),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(default='productos/default.jpg', upload_to='productos/'),
        ),
        migrations.AlterField(
            model_name='restaurante',
            name='costo_envio',
            field=models.DecimalField(decimal_places=2, default=2.99, max_digits=6),
        ),
        migrations.AlterField(
            model_name='restaurante',
            name='imagen',
            field=models.ImageField(default='restaurantes/default.jpg', upload_to='restaurantes/'),
        ),
        migrations.AlterField(
            model_name='restaurante',
            name='tiempo_entrega',
            field=models.CharField(default='30-40 min', max_length=20),
        ),
    ]
